name: CI/CD Pipeline

on:
  push:
    branches: [main, DEV_Zidan]
  pull_request:
    branches: [main]

jobs:
  # Job untuk testing dan linting
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting (optional)
        run: npm run lint || echo "No lint script found"
        continue-on-error: true

      - name: Run tests (optional)
        run: npm test || echo "No test script found"
        continue-on-error: true

      - name: Build project
        run: npm run build